apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-8ude
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tenant/appstudio/devfile-sample-python-basic-8ude@sha256:41f60cd8859d4487476bf7d2846187a5fe0839faf99d51a416d7db5ead29242d
        name: my-python
        resources: {}
status: {}
